# Generated by Django 3.2 on 2021-04-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=150)),
                ('project_description', models.TextField(max_length=10000)),
                ('groupe_membrs', models.ManyToManyField(to='graduation.User')),
            ],
        ),
    ]
