# Generated by Django 3.2 on 2021-04-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='groupe_membrs',
            new_name='group_membrs',
        ),
    ]
