# Generated by Django 3.2 on 2021-04-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0004_rename_group_membrs_project_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
