# Generated by Django 3.2 on 2021-04-23 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0005_remove_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graduation.user')),
                ('st_num', models.IntegerField(max_length=10)),
                ('project_degree', models.IntegerField(max_length=1)),
            ],
            bases=('graduation.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graduation.user')),
                ('t_num', models.IntegerField(max_length=10)),
                ('degree', models.IntegerField(max_length=1)),
            ],
            bases=('graduation.user',),
        ),
    ]
