# Generated by Django 3.2 on 2021-04-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0006_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(max_length=150),
        ),
    ]
