# Generated by Django 3.2 on 2021-04-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0008_auto_20210423_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_supervisor',
        ),
        migrations.AlterField(
            model_name='project',
            name='group_members',
            field=models.ManyToManyField(to='graduation.User'),
        ),
    ]
