# Generated by Django 3.2 on 2021-04-23 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0010_auto_20210423_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_supervisor',
        ),
    ]
