# Generated by Django 3.2 on 2021-05-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0015_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=9),
        ),
    ]
