# Generated by Django 3.2 on 2021-05-09 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0016_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduation.project')),
                ('project_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduation.teacher')),
            ],
        ),
    ]
