# Generated by Django 3.2 on 2021-05-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0017_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=9),
        ),
    ]
