# Generated by Django 3.2 on 2021-05-09 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0018_meeting_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('report', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduation.project')),
                ('project_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduation.teacher')),
            ],
        ),
    ]
