# Generated by Django 3.2 on 2021-05-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0019_progressreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
