# Generated by Django 3.2 on 2021-05-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0020_alter_meeting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='project_supervisor',
        ),
        migrations.AddField(
            model_name='meeting',
            name='project_supervisor',
            field=models.ManyToManyField(to='graduation.Teacher'),
        ),
    ]
