# Generated by Django 3.2 on 2021-05-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0021_auto_20210512_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='teacher_replay',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
